services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      SERVER_NAME: "PEHLA SERVER"
    ports:
      - "5001:7000"

  server2:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      SERVER_NAME: "DUSRA SERVER"
    ports:
      - "5002:7000"

  server3:
    build: ./server
    env_file:
      - ./server/.env
    environment:
      SERVER_NAME: "TESRA SERVER"
    ports:
      - "5003:7000"