services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf

  gateway:
    build: ./backend/gateway
    env_file:
      - ./backend/gateway/.env
    environment:
      SERVER_NAME: "PEHLA GATEWAY"
    ports:
      - "8000:8000"  

  gateway1:
    build: ./backend/gateway1
    env_file:
      - ./backend/gateway1/.env
    environment:
      SERVER_NAME: "DUSRA GATEWAY"
    ports:
      - "8001:8001"


  auth:
    build: ./backend/services/auth
    env_file:
      - ./backend/services/auth/.env
    environment:
      SERVER_NAME: "AUTH SERVICE"
    ports:
      - "3000:3000"


  product:
    build: ./backend/services/product
    env_file:
      - ./backend/services/product/.env
    environment:
      SERVER_NAME: "PRODUCT SERVICE"
    ports:
      - "3002:3002"

  order:
    build: ./backend/services/order
    env_file:
      - ./backend/services/order/.env
    environment:
      SERVER_NAME: "ORDER SERVICE"
    ports:
      - "3001:3001"      
   
    